version: '3.7'
services:
  frontend:
    container_name: petclinic-angular
    image: nokdev/petclinicangular:latest
    deploy:
      replicas: 2
    ports:
      - "8080:8080"
    networks:
      - pc-network
    depends_on:
      - "backend"